"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.colors = void 0;
var palette_1 = require("./palette");
exports.colors = {
    /**
     * General
     */
    primary: palette_1.palette.primary[500],
    primary_bold: palette_1.palette.primary[600],
    primary_text_normal: palette_1.palette.primary[500],
    primary_text_hover: palette_1.palette.primary[900],
    secondary: palette_1.palette.secondary[500],
    secondary_text_normal: palette_1.palette.secondary[500],
    secondary_text_hover: palette_1.palette.secondary[100],
    page_background: palette_1.palette.neutral[50],
    overlay_background: palette_1.palette.neutral[100],
    divider_color: palette_1.palette.neutral[100],
    shadow_color: palette_1.palette.neutral[900],
    surface: palette_1.palette.neutral[0],
    link_color: palette_1.palette.primary[500],
    link_hover: palette_1.palette.primary[900],
    text_color: palette_1.palette.neutral[900],
    /**
     * Buttons
     */
    segmentDivider_color: palette_1.palette.primary[700],
    button_default_primary_border_normal: "transparent",
    button_default_primary_border_hover: "transparent",
    button_default_primary_border_active: "transparent",
    button_default_primary_background_normal: palette_1.palette.primary[500],
    button_default_primary_background_hover: palette_1.palette.primary[900],
    button_default_primary_background_active: palette_1.palette.primary[900],
    button_default_primary_text_normal: palette_1.palette.primary[900],
    button_default_primary_text_hover: palette_1.palette.primary[100],
    button_default_primary_text_active: palette_1.palette.primary[100],
    button_outlined_primary_border_normal: palette_1.palette.primary[500],
    button_outlined_primary_border_hover: palette_1.palette.primary[900],
    button_outlined_primary_border_active: palette_1.palette.primary[900],
    button_outlined_primary_background_normal: "transparent",
    button_outlined_primary_background_hover: "transparent",
    button_outlined_primary_background_active: "transparent",
    button_outlined_primary_text_normal: palette_1.palette.primary[500],
    button_outlined_primary_text_hover: palette_1.palette.primary[900],
    button_outlined_primary_text_active: palette_1.palette.primary[900],
    button_default_secondary_border_normal: "transparent",
    button_default_secondary_border_hover: "transparent",
    button_default_secondary_border_active: "transparent",
    button_default_secondary_background_normal: palette_1.palette.secondary[500],
    button_default_secondary_background_hover: palette_1.palette.secondary[900],
    button_default_secondary_background_active: palette_1.palette.secondary[900],
    button_default_secondary_text_normal: palette_1.palette.secondary[900],
    button_default_secondary_text_hover: palette_1.palette.secondary[100],
    button_default_secondary_text_active: palette_1.palette.secondary[100],
    button_outlined_secondary_border_normal: palette_1.palette.secondary[500],
    button_outlined_secondary_border_hover: palette_1.palette.secondary[900],
    button_outlined_secondary_border_active: palette_1.palette.secondary[900],
    button_outlined_secondary_background_normal: "transparent",
    button_outlined_secondary_background_hover: "transparent",
    button_outlined_secondary_background_active: "transparent",
    button_outlined_secondary_text_normal: palette_1.palette.secondary[500],
    button_outlined_secondary_text_hover: palette_1.palette.secondary[900],
    button_outlined_secondary_text_active: palette_1.palette.secondary[900],
    button_default_neutral_border_normal: "transparent",
    button_default_neutral_border_hover: "transparent",
    button_default_neutral_border_active: "transparent",
    button_default_neutral_background_normal: palette_1.palette.neutral[0],
    button_default_neutral_background_hover: palette_1.palette.neutral[300],
    button_default_neutral_background_active: palette_1.palette.neutral[900],
    button_default_neutral_text_normal: palette_1.palette.neutral[900],
    button_default_neutral_text_hover: palette_1.palette.neutral[900],
    button_default_neutral_text_active: palette_1.palette.neutral[0],
    button_outlined_neutral_border_normal: palette_1.palette.neutral[500],
    button_outlined_neutral_border_hover: palette_1.palette.neutral[900],
    button_outlined_neutral_border_active: palette_1.palette.neutral[900],
    button_outlined_neutral_background_normal: "transparent",
    button_outlined_neutral_background_hover: "transparent",
    button_outlined_neutral_background_active: "transparent",
    button_outlined_neutral_text_normal: palette_1.palette.neutral[500],
    button_outlined_neutral_text_hover: palette_1.palette.neutral[900],
    button_outlined_neutral_text_active: palette_1.palette.neutral[900],
    button_default_green_border_normal: "transparent",
    button_default_green_border_hover: "transparent",
    button_default_green_border_active: "transparent",
    button_default_green_background_normal: palette_1.palette.green[500],
    button_default_green_background_hover: palette_1.palette.green[900],
    button_default_green_background_active: palette_1.palette.green[900],
    button_default_green_text_normal: palette_1.palette.neutral[900],
    button_default_green_text_hover: palette_1.palette.green[100],
    button_default_green_text_active: palette_1.palette.green[100],
    button_outlined_green_border_normal: palette_1.palette.green[500],
    button_outlined_green_border_hover: palette_1.palette.green[900],
    button_outlined_green_border_active: palette_1.palette.green[900],
    button_outlined_green_background_normal: "transparent",
    button_outlined_green_background_hover: "transparent",
    button_outlined_green_background_active: "transparent",
    button_outlined_green_text_normal: palette_1.palette.green[500],
    button_outlined_green_text_hover: palette_1.palette.green[900],
    button_outlined_green_text_active: palette_1.palette.green[900],
    button_default_red_border_normal: "transparent",
    button_default_red_border_hover: "transparent",
    button_default_red_border_active: "transparent",
    button_default_red_background_normal: palette_1.palette.red[500],
    button_default_red_background_hover: palette_1.palette.red[900],
    button_default_red_background_active: palette_1.palette.red[900],
    button_default_red_text_normal: palette_1.palette.red[900],
    button_default_red_text_hover: palette_1.palette.red[100],
    button_default_red_text_active: palette_1.palette.red[100],
    button_outlined_red_border_normal: palette_1.palette.red[500],
    button_outlined_red_border_hover: palette_1.palette.red[900],
    button_outlined_red_border_active: palette_1.palette.red[900],
    button_outlined_red_background_normal: "transparent",
    button_outlined_red_background_hover: "transparent",
    button_outlined_red_background_active: "transparent",
    button_outlined_red_text_normal: palette_1.palette.red[500],
    button_outlined_red_text_hover: palette_1.palette.red[900],
    button_outlined_red_text_active: palette_1.palette.red[900],
    button_select_neutral_border_normal: "transparent",
    button_select_neutral_border_hover: "transparent",
    button_select_neutral_border_active: "transparent",
    button_select_neutral_background_normal: palette_1.palette.neutral[0],
    button_select_neutral_background_hover: palette_1.palette.secondary[100],
    button_select_neutral_background_active: palette_1.palette.secondary[300],
    button_select_neutral_text_normal: palette_1.palette.neutral[900],
    button_select_neutral_text_hover: palette_1.palette.neutral[900],
    button_select_neutral_text_active: palette_1.palette.neutral[900],
    nav_background: palette_1.palette.neutral[0],
    subnav_background: palette_1.palette.neutral[200],
    nav_shadow: palette_1.palette.neutral[500],
    navItem_normal: palette_1.palette.neutral[700],
    navItem_hovered: palette_1.palette.secondary[500],
    navItem_active: palette_1.palette.primary[500],
    /**
     * Fields
     */
    field_select_menu_background: palette_1.palette.neutral[0],
    fieldAccent_normal: palette_1.palette.neutral[100],
    fieldAccent_focused: palette_1.palette.primary[500],
    /**
     * Charts
     */
    chart_radar_axis_start: palette_1.palette.neutral[500],
    chart_radar_axis_end: palette_1.palette.neutral[100],
    chart_radar_levels: palette_1.palette.neutral[300],
    chart_radar_set1_label: palette_1.palette.primary[700],
    chart_radar_set1_outline: palette_1.palette.primary[500],
    chart_radar_set1_fill: "".concat(palette_1.palette.primary[500], "22"),
    chart_radar_set2_label: palette_1.palette.secondary[700],
    chart_radar_set2_outline: palette_1.palette.secondary[500],
    chart_radar_set2_fill: "".concat(palette_1.palette.secondary[500], "22"),
    chart_radar_set3_label: palette_1.palette.green[700],
    chart_radar_set3_outline: palette_1.palette.green[500],
    chart_radar_set3_fill: "".concat(palette_1.palette.green[500], "22"),
    /**
     * Sliders
     */
    slider_background: "#D8EDE9",
    slider_text_area_background: "#BCE2DB",
};
